defaults:
  - _self_

  - core: default

  - data: imagenet
  - model: classifier

  - trainer: default
  - callbacks: default
  - logger: wandb
  - hydra: default

  - experiment: null

  - optional local: default

  - debug: null

train: True
test: True

ckpt_path: null

callbacks:
  model_checkpoint:
    monitor: "val/acc"
