defaults:
  - _self_

  - core: default

  - data: cifar10-diffusion
  - model: diffusion

  - trainer: default
  - callbacks: default
  - logger: wandb
  - hydra: default

  - experiment: null

  - optional local: default

  - debug: null

train: True
test: True

ckpt_path: null

trainer:
  limit_val_batches: 1
  limit_test_batches: 1

callbacks:
  model_checkpoint:
    monitor: null
