_target_: lightning.pytorch.loggers.wandb.WandbLogger

project: ${core.project_name}
entity: ${core.entity}
save_dir: ${core.output_dir}

log_model: False
mode: online

name: ${core.name}
tags: ${core.tags}
group: ${core.group}
